config/routes.rb
TweeterStorage::Application.routes.draw do
  resources :leads

  resources :tweets

  resources :queries do
    member do
      post :make_query
    end
  end

match "leads/show_parsed" => "leads#show_parsed"

end

app/models/tweet.rb
require 'oauth'
require 'json'
require 'open-uri'
require 'net/http'
require 'uri'
require 'httpclient'

# require 'wombat'
# require 'open_uri_redirections'

class Tweet < ActiveRecord::Base
  attr_accessible :handle, :message, :query_id, :tweet_id, :tweeted_on
  belongs_to :query
  has_many :leads

  def parse_url(full_url)

    full_url.slice!("https://attendee.gotowebinar.com")
    Wombat.crawl do
      base_url "https://attendee.gotowebinar.com"
      path full_url
      headline "xpath=//a"
      title "xpath=//h2"
      #subheading "css=p.subheading"
      #what_is "css=.teaser h3", :list
      # links do
        #   explore 'xpath=//*[@id="wrapper"]/div[1]/div/ul/li[1]/a' do |e|
        #     e.gsub(/Explore/, "Love")
        #   end

        # search 'css=.search'
        #features 'css=.features'
        #blog 'css=.blog'
      # end
    end
  end

  def get_abs_url(url)
    # $stderr.reopen("err", "w")
    # open(url)
    open(url, :allow_redirections => :safe) do |resp|
      # open(url) do |resp|
      resp.base_uri.to_s
    end
  end

  def parse_tweet
    # ADD CODE TO ITERATE THROUGH EACH TWEET AND PRINT ITS TEXT
    unless self.nil?
      # name = tweet["user"]["name"]
      text = self.message
      puts text

      strings = text.split
      strings.each do |string|
        if string =~ /http/
          begin
            full_url = self.get_abs_url(string)
            puts full_url
            if full_url =~ /register|rt/
              puts parse_url(full_url)
              res = parse_url(full_url)
              if (res["headline"] =~ /@/ and Lead.find_by_link(string).nil?)
                puts "!!!!!!!!!!!!!!!!!!!!!1"
                Lead.create(:email=>res["headline"], :link=>string, :tweet_id=>self.id, :type_cd=>"", :webinar_title=>res["title"])
                # CSV.open("twitter_emal.csv", "a") do |csv|
                #   csv << [string, res]
                # end
              else Lead.create(:link=>string, :tweet_id=>self.id, :type_cd=>"")
              end
            end
          rescue
          end


          # puts if(full_url =~ /rigister/)
        end
      end

      puts "================================="
    end
  end

  def self.parse_parse_tweet
    Tweet.all.each do |tweet|
      if tweet.leads.== []
        puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~``"
        tweet.parse_tweet
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet_id %><br />
    <%= f.text_field :tweet_id %>
  </div>
  <div class="field">
    <%= f.label :tweeted_on %><br />
    <%= f.datetime_select :tweeted_on %>
  </div>
  <div class="field">
    <%= f.label :query_id %><br />
    <%= f.number_field :query_id %>
  </div>
  <div class="field">
    <%= f.label :handle %><br />
    <%= f.text_field :handle %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>
<%= button_to "GO TO QUERIES", queries_path, method: :get %>

<table>
  <tr>
    <th>Tweet |</th>
    <th>Tweeted on |</th>
    <th>Query |</th>
    <th>Handle |</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.tweet_id %></td>
    <td><%= tweet.tweeted_on %></td>
    <td><%= tweet.query_id %></td>
    <td><%= tweet.handle %></td>
    <td><%= tweet.message %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br/>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tweet:</b>
  <%= @tweet.tweet_id %>
</p>

<p>
  <b>Tweeted on:</b>
  <%= @tweet.tweeted_on %>
</p>

<p>
  <b>Query:</b>
  <%= @tweet.query_id %>
</p>

<p>
  <b>Handle:</b>
  <%= @tweet.handle %>
</p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>