config/routes.rb
TweeterStorage::Application.routes.draw do
  resources :leads

  resources :tweets

  resources :queries do
    member do
      post :make_query
    end
  end

match "leads/show_parsed" => "leads#show_parsed"

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  attr_accessible :email, :link, :tweet_id, :type_cd, :webinar_title
  belongs_to :tweet

  scope :not_parsed, :conditions => 'leads.email is null'
  scope :parsed, :conditions => 'leads.email is not null'

  def reparse_email
      begin
        puts "in begin"
        puts self.tweet
        full_url = self.tweet.get_abs_url(self.link)
        puts full_url
        if full_url =~ /register|rt/
          puts "yeeeeeeeeeeeeeeeeees"
          res = self.tweet.parse_url(full_url)
          puts res
          if res["headline"] =~ /@/
            puts "!!!!!!!!!!!!!!!!!!!!!1"
            self.email = res["headline"]
            self.webinar_title = res["title"]
            self.save
            puts "1 more add ==============================================="
            return self
            # Lead.create(:email=>res["headline"], :link=>string, :tweet_id=>self.id, :type_cd=>"", :webinar_title=>res["title"])
            # CSV.open("twitter_emal.csv", "a") do |csv|
            #   csv << [string, res]
            # end
          #else Lead.create(:link=>string, :tweet_id=>self.id, :type_cd=>"")
          end
        end
      rescue
      end
  end

  def self.batch_reparse

    newly = []
    Lead.not_parsed.each do |lead|
      l = lead.reparse_email
      puts l.class
      unless l.nil?
        newly << l
      end
    end
    return newly
  end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  def show_parsed
    @leads = Lead.parsed.order('updated_at')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  def newly_parse
    @leads = Lead.parsed

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @lead = Lead.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/new
  # GET /leads/new.json
  def new
    @lead = Lead.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/1/edit
  def edit
    @lead = Lead.find(params[:id])
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(params[:lead])

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render json: @lead, status: :created, location: @lead }
      else
        format.html { render action: "new" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads/1
  # PUT /leads/1.json
  def update
    @lead = Lead.find(params[:id])

    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet_id %><br />
    <%= f.number_field :tweet_id %>
  </div>
  <div class="field">
    <%= f.label :webinar_title %><br />
    <%= f.text_field :webinar_title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :type_cd %><br />
    <%= f.text_field :type_cd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<h1>Listing leads</h1>
<%= button_to 'show parsed leads', {:controller => "leads", :action => "show_parsed"} %>
<br>
<%= button_to 'Go To Query', queries_path, method: :get %>
<br>
<%= button_to 'Go To Tweet', tweets_path, method: :get %>

<table>
  <tr>
    <th>Tweet</th>
    <th>Webinar title</th>
    <th>Link</th>
    <th>Email</th>
    <th>Type cd</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leads.each do |lead| %>
  <tr>
    <td><%= lead.tweet_id %></td>
    <td><%= lead.webinar_title %></td>
    <td><%= lead.link %></td>
    <td><%= lead.email %></td>
    <td><%= lead.type_cd %></td>
    <td><%= link_to 'Show', lead %></td>
    <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
    <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tweet:</b>
  <%= @lead.tweet_id %>
</p>

<p>
  <b>Webinar title:</b>
  <%= @lead.webinar_title %>
</p>

<p>
  <b>Link:</b>
  <%= @lead.link %>
</p>

<p>
  <b>Email:</b>
  <%= @lead.email %>
</p>

<p>
  <b>Type cd:</b>
  <%= @lead.type_cd %>
</p>


<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/leads/show_parsed.html.erb
<h1>Listing leads</h1>

<table>
  <tr>
    <th>Tweet</th>
    <th>Webinar title</th>
    <th>Link</th>
    <th>Email</th>
    <th>Type cd</th>
    <th>Update_time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.tweet_id %></td>
        <td><%= lead.webinar_title %></td>
        <td><%= lead.link %></td>
        <td><%= lead.email %></td>
        <td><%= lead.type_cd %></td>
        <td><%= lead.updated_at %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Lead', new_lead_path %>