config/routes.rb
TweeterStorage::Application.routes.draw do
  resources :leads

  resources :tweets

  resources :queries do
    member do
      post :make_query
    end
  end

match "leads/show_parsed" => "leads#show_parsed"

end

app/models/query.rb
require 'twitter'
require 'rubygems'
require 'oauth'
require 'json'
require 'date'

class Query < ActiveRecord::Base
  attr_accessible :handle, :hash_tag, :keywords
  has_many :tweets



  def search_tweet(query)
    puts query
    consumer_key = OAuth::Consumer.new(CONSUMER_KEY, CONSUMER_SECRET)
    access_token = OAuth::Token.new(ACCESS_KEY, ACCESS_SECRET)

    baseurl = "https://api.twitter.com"
    path = "/1.1/search/tweets.json"

    last_tw_id = Tweet.last.nil? ? '' : Tweet.last.tweet_id.to_i
    puts last_tw_id
    query = URI.encode_www_form(
      "q" => query,
      # "screen_name" => "twitterapi",
      "count" => 100,
      "lang" => 'en',
      "since_id" => ''
    )
    address = URI("#{baseurl}#{path}?#{query}")
    request = Net::HTTP::Get.new address.request_uri

    # Set up HTTP.
    http = Net::HTTP.new address.host, address.port
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    # If you entered your credentials in the first
    # exercise, no need to enter them again here. The
    # ||= operator will only assign these values if
    # # they are not already set.
    #     consumer_key ||= OAuth::Consumer.new "ENTER IN EXERCISE 1", ""
    #     access_token ||= OAuth::Token.new "ENTER IN EXERCISE 1", ""

    # Issue the request.
    request.oauth! http, consumer_key, access_token
    http.start
    response = http.request request

    # Parse and print the Tweet if the response code was 200
    #tweets = nil
    if response.code == '200' then
      tweets = JSON.parse(response.body)["statuses"]
      # puts JSON.pretty_generate(tweets)
      # puts tweets.count
      # puts tweets.class
      # puts tweets["statuses"].class
      #print_timeline(tweets)
      tweets.each do |tweet|
        if Tweet.find_by_tweet_id(tweet["id_str"]).nil?
          t = Tweet.create(:message=> tweet["text"], :handle=>tweet["user"]["id_str"], :tweet_id=>tweet["id_str"], :tweeted_on=>tweet["created_at"], :query_id=>self.id)
          t.parse_tweet
        end
      end
    end
  end

  def generate_query(s, minus)
    today_string = (Date.today - minus).to_s
    query = s + ' until:'+today_string
  end

  def generate_hash
    unless self.hash_tag[0]=='#'
      hash ="#"+ self.hash_tag
    else
      hash =self.hash_tag
    end
    hash
  end

  def generate_handle
    unless self.handle[0]=='@'
      hand ="#"+ self.handle
    else
      hand = self.handle
    end
    hand
  end

  def make_twitter_query(minus=7)
    puts self
    if self.handle.length > 0
      s = generate_handle
    elsif self.hash_tag.length > 0
      s = generate_hash
    else
      s = self.keywords
    end
    (0..minus).to_a.reverse.each do |day|
      q = generate_query(s,day)
      self.search_tweet(q)
    end
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  # GET /queries
  # GET /queries.json
  def index
    @queries = Query.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @queries }
    end
  end

  # GET /queries/1
  # GET /queries/1.json
  def show
    @query = Query.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @query }
    end
  end

  # GET /queries/new
  # GET /queries/new.json
  def new
    @query = Query.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @query }
    end
  end

  # GET /queries/1/edit
  def edit
    @query = Query.find(params[:id])
  end

  # POST /queries
  # POST /queries.json
  def create
    @query = Query.new(params[:query])

    respond_to do |format|
      if @query.save
        format.html { redirect_to @query, notice: 'Query was successfully created.' }
        format.json { render json: @query, status: :created, location: @query }
      else
        format.html { render action: "new" }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /queries/1
  # PUT /queries/1.json
  def update
    @query = Query.find(params[:id])

    respond_to do |format|
      if @query.update_attributes(params[:query])
        format.html { redirect_to @query, notice: 'Query was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queries/1
  # DELETE /queries/1.json
  def destroy
    @query = Query.find(params[:id])
    @query.destroy

    respond_to do |format|
      format.html { redirect_to queries_url }
      format.json { head :no_content }
    end
  end

  def make_query
    @query = Query.find(params[:id])
    puts @query
    @query.make_twitter_query
    redirect_to leads_path
  end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/_form.html.erb
<%= form_for(@query) do |f| %>
  <% if @query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@query.errors.count, "error") %> prohibited this query from being saved:</h2>

      <ul>
      <% @query.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :hash_tag %><br />
    <%= f.text_field :hash_tag %>
  </div>
  <div class="field">
    <%= f.label :handle %><br />
    <%= f.text_field :handle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/queries/edit.html.erb
<h1>Editing query</h1>

<%= render 'form' %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', queries_path %>

app/views/queries/index.html.erb
<h1>Listing queries</h1>

<table>
  <tr>
    <th>Keywords |</th>
    <th>Hash tag |</th>
    <th>Handle</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @queries.each do |query| %>
  <tr>
    <td><%= query.keywords %></td>
    <td><%= query.hash_tag %></td>
    <td><%= query.handle %></td>
    <td><%= button_to 'Query It!', {:controller => 'queries', :action => 'make_query', :id =>query.id} %></td>
    <td><%= link_to 'Show', query %></td>
    <td><%= link_to 'Edit', edit_query_path(query) %></td>
    <td><%= link_to 'Destroy', query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Query', new_query_path %>

app/views/queries/new.html.erb
<h1>New query</h1>

<%= render 'form' %>

<%= link_to 'Back', queries_path %>

app/views/queries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Keywords:</b>
  <%= @query.keywords %>
</p>

<p>
  <b>Hash tag:</b>
  <%= @query.hash_tag %>
</p>

<p>
  <b>Handle:</b>
  <%= @query.handle %>
</p>


<%= link_to 'Edit', edit_query_path(@query) %> |
<%= link_to 'Back', queries_path %>